### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by leohotfn** [Awesome-a3ther/LEO-s-subway#1]
我还以为你这么快就提交代码了，你吓到我了....
我還以為你這麼快就提交代碼了，你嚇到我了....
you submit your code so fast that you scared me...
私はあなたが私を怖がって、あなたはコードを提出するので、迅速なと思っていました....

**Comment by Awesome-a3ther** [comment]
still cannot get used to github...

**Comment by leohotfn** [comment]
Let me help you.

**Comment by Awesome-a3ther** [comment]
i miss JINGJING.
